import { ReactNode } from 'react';
import { FieldType } from '@/types/formField';
import {
  AlignLeft,
  BarChart3,
  Calendar,
  CalendarClock,
  CalendarDays,
  CheckSquare,
  ChevronDown,
  Circle,
  Code2,
  DollarSign,
  Droplet,
  EyeOff,
  Upload,
  FileText,
  SquareFunction as FormulaIcon,
  Gauge,
  GitBranch,
  Heading,
  Hash,
  Image,
  Key,
  LayoutDashboard,
  LayoutGrid,
  LayoutList,
  ListChecks,
  ListPlus,
  MapPin,
  Mic,
  PenTool,
  Phone,
  Search,
  Share2,
  SlidersHorizontal,
  Star,
  ToggleRight,
  Video,
  Link2,
  Clock,
  Mail,
  Minus,
  Users,
} from 'lucide-react';

const iconClass = 'h-4 w-4';

export const FIELD_ICONS: Record<FieldType, ReactNode> = {
  text: <Heading className={iconClass} />,
  email: <Mail className={iconClass} />,
  tel: <Phone className={iconClass} />,
  number: <Hash className={iconClass} />,
  url: <Link2 className={iconClass} />,
  password: <Key className={iconClass} />,
  textarea: <AlignLeft className={iconClass} />,
  select: <ListChecks className={iconClass} />,
  radio: <Circle className={iconClass} />,
  checkbox: <CheckSquare className={iconClass} />,
  date: <Calendar className={iconClass} />,
  time: <Clock className={iconClass} />,
  'datetime-local': <CalendarClock className={iconClass} />,
  file: <Upload className={iconClass} />,
  range: <SlidersHorizontal className={iconClass} />,
  color: <Droplet className={iconClass} />,
  hidden: <EyeOff className={iconClass} />,
  lookup: <Search className={iconClass} />,
  formula: <FormulaIcon className={iconClass} />,
  conditional: <GitBranch className={iconClass} />,
  dependent: <GitBranch className={iconClass} />,
  rating: <Star className={iconClass} />,
  signature: <PenTool className={iconClass} />,
  'section-break': <Minus className={iconClass} />,
  'page-break': <FileText className={iconClass} />,
  heading: <Heading className={iconClass} />,
  paragraph: <AlignLeft className={iconClass} />,
  banner: <LayoutDashboard className={iconClass} />,
  'picture-choice': <Image className={iconClass} />,
  multiselect: <CheckSquare className={iconClass} />,
  switch: <ToggleRight className={iconClass} />,
  'multiple-choice': <Circle className={iconClass} />,
  checkboxes: <CheckSquare className={iconClass} />,
  'choice-matrix': <LayoutGrid className={iconClass} />,
  'date-range': <CalendarDays className={iconClass} />,
  ranking: <BarChart3 className={iconClass} />,
  'star-rating': <Star className={iconClass} />,
  'opinion-scale': <Gauge className={iconClass} />,
  'rich-text': <FileText className={iconClass} />,
  address: <MapPin className={iconClass} />,
  currency: <DollarSign className={iconClass} />,
  'voice-recording': <Mic className={iconClass} />,
  'submission-picker': <ListPlus className={iconClass} />,
  subform: <LayoutList className={iconClass} />,
  'section-collapse': <ChevronDown className={iconClass} />,
  divider: <Minus className={iconClass} />,
  'html-snippet': <Code2 className={iconClass} />,
  image: <Image className={iconClass} />,
  video: <Video className={iconClass} />,
  'pdf-viewer': <FileText className={iconClass} />,
  'social-links': <Share2 className={iconClass} />,
  'member-search': <Users className={iconClass} />,
  'momence-sessions': <CalendarDays className={iconClass} />,
} as Record<FieldType, ReactNode>;
